---
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: use the "errors" package instead

# The most valuable linters; they are required to pass for PR to be merged.
linters:
  disable-all: true
  enable:
    - depguard
    - goimports
    - ineffassign
    - govet
    - staticcheck

issues:
  exclude-use-default: false
