dist: trusty
sudo: required
language: go

go:
- 1.13.x

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

env:
- MYSQL_IMAGE=mysql/mysql-server:5.5
- MYSQL_IMAGE=mysql/mysql-server:5.6
- MYSQL_IMAGE=mysql/mysql-server:5.7
- MYSQL_IMAGE=mysql/mysql-server:8.0
- MYSQL_IMAGE=mariadb:5.5
- MYSQL_IMAGE=mariadb:10.0
- MYSQL_IMAGE=mariadb:10.1
- MYSQL_IMAGE=mariadb:10.2
- MYSQL_IMAGE=mariadb:10.3
- MYSQL_IMAGE=percona/percona-server:5.6
- MYSQL_IMAGE=percona/percona-server:5.7
- MYSQL_IMAGE=percona/percona-server:8.0
- MYSQL_IMAGE=percona:5.5
- MYSQL_IMAGE=percona:5.6
- MYSQL_IMAGE=percona:5.7
- MYSQL_IMAGE=percona:8.0

services:
- docker

go_import_path: github.com/percona/mysqld_exporter

install:
  # install reviewdog and golangci-lin
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

before_script:
  # static analyze
  - bin/golangci-lint run -c=.golangci.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
  - sudo service mysql stop
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
- make
- make test

notifications:
  email: false
