# see CONTRIBUTING.md
---
services:
  mysql:
    image: ${MYSQL_IMAGE:-mysql/mysql-server:8.0.32}
    container_name: mysqld_exporter_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_HOST=%
      - INIT_ROCKSDB=1
    ports:
      - "3306:3306"
    healthcheck:
      test: [
        "CMD-SHELL",
        "if command -v mysql >/dev/null; then \
          mysql -uroot -e 'SELECT 1;'; \
        else \
          mariadb -uroot -e 'SELECT 1;'; \
        fi || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
